version: "3.7" #Docker Engine release 18.06.0+

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

############ Nginx services ############
  nginx:
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - frontend
      - backend

############ MySQL services ############
  mysql:
    build:
      context: ./mysql/${MYSQL_VERSION}
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql/${MYSQL_VERSION}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - frontend
      - backend

############ Redis ############
  redis:
    build:
      context: ./redis/${REDIS_VERSION}
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/redis/${REDIS_VERSION}:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - frontend
      - backend
############ Memcached ############
  memcached:
    build: ./memcached
    volumes:
      - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
    ports:
      - "${MEMCACHED_HOST_PORT}:11211"
    networks:
      - frontend
      - backend

